version: "3.7"
services:
  database:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - ./db:/data/db
    networks:
      - finalpjnet
    restart: unless-stopped
  
  api:
    build: ./Server-api-temp
    ports:
      - '8886:8886'
    environment:
      - MONGODB_URL = mongodb://root:1234@database:27017/finalpj?authSource=admin
    networks:
      - finalpjnet
    depends_on:
      - database
    restart: unless-stopped

  fontend:
    build: ./fontend
    ports:
      - 3000:80
    depends_on:
      - api
    networks:
      - finalpjnet
    restart: unless-stopped
  nginx:
    build: ./nginx
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - fontend
    networks:
      - finalpjnet
    restart: unless-stopped

networks:
  finalpjnet:
    driver: bridge
